### ISSUE TITLE
add web components in bootstrapcdn

### ISSUE THREAD

**Issue by codehangen** [jsdelivr/bootstrapcdn#1778]
Hi all. 

I would like to know if it is possible to add bootstrap web components in bootstrap cdn. So... *Is it possible to add bootstrap web components in bootstrapcdn?*

**Comment by jimaek** [comment]
Do you have an example of what exactly you want to do?
Thanks

**Comment by jimaek** [comment]
The BootstrapCDN at the current stage is a jsDelivr endpoint that pulls files from the official Bootstrap NPM packages.

So I dont understand the question because if Bootstrap is not distributing web components then obviously we cant add them.

But also there is nothing stopping you from using any other web component made by anyone and hosted on Github or NPM since jsDelivr supports both.

The only question that I am not sure about is if they are going to work without the correct HTML mime-type. @MartinKolarik

**Comment by MartinKolarik** [comment]
@codehangen in that case you're welcome to do it and distribute it as a separate package via npm and jsDelivr.

**Comment by MartinKolarik** [comment]
Please see https://www.jsdelivr.com/ - you'll get it on our CDN by simply publishing it to npm.
